Updated to new query and result form yahoo weather api
kostspielig/eatout pull request #2
Opened 2016-10-21 14:42 UTC by kostspielig

Fixes #1

2016-10-21 14:46 UTC, arximboldi requested changes
Very good! Pero quita el console.log... :smile:

2016-10-21 14:46 UTC, arximboldi commented on src/coffee/services.coffee
> +                console.log "RECEIVED WHATEVER"
Creo que este console.log sobra...

2016-10-21 14:58 UTC, kostspielig commented
Sure, I was testing your reviewer skills :laughing:

2016-10-23 12:37 UTC, arximboldi approved these changes

2016-10-23 12:37 UTC, merged